queue_image   = '/Users/schuyler.smith@nutrien.com/Desktop/pyAutoTest/images/queue.png'
empty_image   = '/Users/schuyler.smith@nutrien.com/Desktop/pyAutoTest/images/empty.png'
bagID_image   = '/Users/schuyler.smith@nutrien.com/Desktop/pyAutoTest/images/bagID.png'
approve_image = '/Users/schuyler.smith@nutrien.com/Desktop/pyAutoTest/images/approve.png'
reject_image  = '/Users/schuyler.smith@nutrien.com/Desktop/pyAutoTest/images/reject.png'
reason_image  = '/Users/schuyler.smith@nutrien.com/Desktop/pyAutoTest/images/reason.png'
yes_image     = '/Users/schuyler.smith@nutrien.com/Desktop/pyAutoTest/images/yes.png'
yes_rej_image = '/Users/schuyler.smith@nutrien.com/Desktop/pyAutoTest/images/yes_reject.png'

ammonifiers_image = '/Users/schuyler.smith@nutrien.com/Desktop/pyAutoTest/images/flags/ammonifiers_na.png'
bacteria_image    = '/Users/schuyler.smith@nutrien.com/Desktop/pyAutoTest/images/flags/bacteria_na.png'
biomass_image     = '/Users/schuyler.smith@nutrien.com/Desktop/pyAutoTest/images/flags/biomass_na.png'
brady_image       = '/Users/schuyler.smith@nutrien.com/Desktop/pyAutoTest/images/flags/brady_na.png'
denitrifier_image = '/Users/schuyler.smith@nutrien.com/Desktop/pyAutoTest/images/flags/denitrifiers_na.png'
fungi_image       = '/Users/schuyler.smith@nutrien.com/Desktop/pyAutoTest/images/flags/fungi_na.png'
mineral_image     = '/Users/schuyler.smith@nutrien.com/Desktop/pyAutoTest/images/flags/mineral_na.png'
mycorrihza_image  = '/Users/schuyler.smith@nutrien.com/Desktop/pyAutoTest/images/flags/mycorrihza_na.png'
n2o_image         = '/Users/schuyler.smith@nutrien.com/Desktop/pyAutoTest/images/flags/n2o_na.png'
nconserv_image    = '/Users/schuyler.smith@nutrien.com/Desktop/pyAutoTest/images/flags/nconserv_na.png'
nfixers_image     = '/Users/schuyler.smith@nutrien.com/Desktop/pyAutoTest/images/flags/nfixers_na.png'
nitri_bal_image   = '/Users/schuyler.smith@nutrien.com/Desktop/pyAutoTest/images/flags/nitri_bal_na.png'
nitrifiers_image  = '/Users/schuyler.smith@nutrien.com/Desktop/pyAutoTest/images/flags/nitrifiers_na.png'
solubilizer_na    = '/Users/schuyler.smith@nutrien.com/Desktop/pyAutoTest/images/flags/solubilization_na.png'

timeout_image     = '/Users/schuyler.smith@nutrien.com/Desktop/pyAutoTest/images/timeout.png'
